name: SSH
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
jobs:
  deploy:
    name: "Deploy to VPS"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.HOST }}

      - name: Stop the server
        run: ssh staging 'sudo systemctl stop api_pyxy.service'

      - name: Check out the source
        run: ssh staging 'cd /var/www/pyxy/api/ && git fetch && git reset --hard origin/master && make install'

      - name: Start the server
        if: ${{ always() }}
        run: ssh staging 'sudo systemctl start api_pyxy.service'
